### ISSUE TITLE
APP crash when start the game again

### ISSUE THREAD

**Issue by Weakey** [ch09830249/Android_Horse_Race#1]
1. Press "Start Game" button to start the game
2. Wait for the game finsih
3. Press "Start Game" button to start the game again
4. Crash happen

2021-10-20 19:31:21.740 2305-2305/com.example.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 2305
    java.lang.IllegalThreadStateException
        at java.lang.Thread.start(Thread.java:724)
        at com.example.myapplication.MainActivity.start_game(MainActivity.kt:259)
        at com.example.myapplication.MainActivity$onCreate$1.onClick(MainActivity.kt:142)
        at android.view.View.performClick(View.java:6608)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by ch09830249** [comment]
The problem has already fixed. The reason is that the same thread was called twice. Thus, my solution is that I establish new thread when a new game starts.
